# Generated by Django 3.0.8 on 2020-09-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='readable_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
