# Generated by Django 3.0.8 on 2020-09-17 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200916_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainableTrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readable_name', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Sustainable Traits',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sustainable_trait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.SustainableTrait'),
        ),
    ]
