# Generated by Django 3.0.8 on 2020-09-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_sustainabletrait_readable_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='readable_name',
        ),
        migrations.RemoveField(
            model_name='continent',
            name='readable_name',
        ),
    ]
